export const ERROR_MESSAGES = {
  AUTH: {
    EMAIL_ALREADY_REGISTERED: 'Email is already registered',
    INVALID_CREDENTIALS: 'Invalid email or password',
    ACCOUNT_SUSPENDED: 'Your account has been suspended',
    ACCOUNT_NOT_FOUND: 'Account not found',
    EMAIL_NOT_FOUND: 'User with this email does not exist',
    INVALID_OR_EXPIRED_RESET_TOKEN: 'Invalid or expired password reset token',
    INVALID_TOKEN_TYPE: 'Invalid token type',
    UNAUTHORIZED_OR_INVALID_TOKEN: 'Unauthorized or invalid token',
    ROLE_NOT_FOUND: 'Specified role does not exist',
  },
  USER: {
    NOT_FOUND: 'User not found',
  },
  VALIDATION: {
    NAME_REQUIRED: 'Name is required',
    EMAIL_REQUIRED: 'Email is required',
    EMAIL_INVALID: 'Must be a valid email address',
    PASSWORD_REQUIRED: 'Password is required',
    PASSWORD_MIN_LENGTH: 'Password must be at least 6 characters long',
    RESET_TOKEN_REQUIRED: 'Reset token is required',
    NEW_PASSWORD_REQUIRED: 'New password is required',
    ROLE_REQUIRED: 'Role is required',
  },
};

export const RESPONSE_MESSAGES = {
  AUTH: {
    REGISTER_SUCCESS: 'User registered successfully',
    LOGIN_SUCCESS: 'User logged in successfully',
    PROFILE_FETCH_SUCCESS: 'User profile fetched successfully',
    FORGOT_PASSWORD_SUCCESS: 'Password reset code sent successfully',
    RESET_PASSWORD_SUCCESS: 'Password reset successfully',
  },
  CART: {
    FETCH_SUCCESS: 'Cart retrieved successfully',
    ADD_ITEM_SUCCESS: 'Item added to cart successfully',
    UPDATE_ITEM_SUCCESS: 'Cart item updated successfully',
    REMOVE_ITEM_SUCCESS: 'Cart item removed successfully',
    CLEAR_SUCCESS: 'Cart cleared successfully',
  },
  ORDERS: {
    CREATE_SUCCESS: 'Order placed successfully',
    FETCH_ALL_SUCCESS: 'Orders fetched successfully',
    FETCH_USER_SUCCESS: 'User orders fetched successfully',
    FETCH_VENDOR_SUCCESS: 'Vendor orders fetched successfully',
    FETCH_NUMBER_SUCCESS: 'Order details fetched by order number successfully',
    FETCH_ONE_SUCCESS: 'Order details fetched successfully',
    UPDATE_STATUS_SUCCESS: 'Order status updated successfully',
  },
  SHIPMENTS: {
    CREATE_SUCCESS: 'Shipment created successfully',
    FETCH_ALL_SUCCESS: 'Shipments fetched successfully',
    FETCH_ORDER_SUCCESS: 'Shipments fetched by order ID successfully',
    FETCH_VENDOR_ORDER_SUCCESS: 'Shipment fetched by order vendor package ID successfully',
    FETCH_AGENT_SUCCESS: 'Shipments fetched by delivery agent ID successfully',
    FETCH_ONE_SUCCESS: 'Shipment details fetched successfully',
    UPDATE_STATUS_SUCCESS: 'Shipment status updated successfully',
    DELETE_SUCCESS: 'Shipment deleted successfully',
  },
  PRODUCTS: {
    FETCH_ALL_SUCCESS: 'Products fetched successfully',
    FETCH_ONE_SUCCESS: 'Product details fetched successfully',
    CREATE_SUCCESS: 'Product created successfully',
    UPDATE_SUCCESS: 'Product updated successfully',
    DELETE_SUCCESS: 'Product deleted successfully',
    CREATE_VARIANT_SUCCESS: 'Product variant created successfully',
    FETCH_VARIANTS_SUCCESS: 'Product variants fetched successfully',
    UPDATE_VARIANT_SUCCESS: 'Product variant updated successfully',
    DELETE_VARIANT_SUCCESS: 'Product variant deleted successfully',
    CREATE_ATTRIBUTE_SUCCESS: 'Product attribute created successfully',
    FETCH_ATTRIBUTES_SUCCESS: 'Product attributes fetched successfully',
    UPDATE_ATTRIBUTE_SUCCESS: 'Product attribute updated successfully',
    DELETE_ATTRIBUTE_SUCCESS: 'Product attribute deleted successfully',
    CREATE_IMAGE_SUCCESS: 'Product image created successfully',
    FETCH_IMAGES_SUCCESS: 'Product images fetched successfully',
    UPDATE_IMAGE_SUCCESS: 'Product image updated successfully',
    DELETE_IMAGE_SUCCESS: 'Product image deleted successfully',
  },
  CATEGORIES: {
    FETCH_ALL_SUCCESS: 'Categories fetched successfully',
    FETCH_ONE_SUCCESS: 'Category details fetched successfully',
    CREATE_SUCCESS: 'Category created successfully',
    UPDATE_SUCCESS: 'Category updated successfully',
    DELETE_SUCCESS: 'Category deleted successfully',
  },
  BRANDS: {
    FETCH_ALL_SUCCESS: 'Brands fetched successfully',
    FETCH_ONE_SUCCESS: 'Brand details fetched successfully',
    CREATE_SUCCESS: 'Brand created successfully',
    UPDATE_SUCCESS: 'Brand updated successfully',
    DELETE_SUCCESS: 'Brand deleted successfully',
  },
  VENDOR_PRODUCTS: {
    CREATE_SUCCESS: 'Vendor product created successfully',
    FETCH_ALL_SUCCESS: 'Vendor products fetched successfully',
    FETCH_VENDOR_SUCCESS: 'Vendor products fetched by vendor ID successfully',
    FETCH_VARIANT_SUCCESS: 'Vendor products fetched by variant ID successfully',
    FETCH_ONE_SUCCESS: 'Vendor product details fetched successfully',
    UPDATE_SUCCESS: 'Vendor product updated successfully',
    DELETE_SUCCESS: 'Vendor product deleted successfully',
  },
  VENDORS: {
    FETCH_ALL_SUCCESS: 'Vendors fetched successfully',
    FETCH_ONE_SUCCESS: 'Vendor details fetched successfully',
  },
  DELIVERY_AGENTS: {
    FETCH_ALL_SUCCESS: 'Delivery agents fetched successfully',
    FETCH_ONE_SUCCESS: 'Delivery agent details fetched successfully',
  },
  COUPONS: {
    CREATE_SUCCESS: 'Coupon created successfully',
    APPLY_SUCCESS: 'Coupon validated and applied successfully',
    RECORD_USAGE_SUCCESS: 'Coupon usage recorded successfully',
    FETCH_ALL_SUCCESS: 'Coupons fetched successfully',
    FETCH_CODE_SUCCESS: 'Coupon details fetched by code successfully',
    FETCH_USAGES_COUPON_SUCCESS: 'Coupon usage history fetched successfully',
    FETCH_USAGES_USER_SUCCESS: 'User coupon usage history fetched successfully',
    FETCH_ONE_SUCCESS: 'Coupon details fetched successfully',
    UPDATE_SUCCESS: 'Coupon updated successfully',
    DELETE_SUCCESS: 'Coupon deleted successfully',
  },
  REVIEWS: {
    CREATE_SUCCESS: 'Review submitted successfully',
    FETCH_ALL_SUCCESS: 'Reviews fetched successfully',
    FETCH_PRODUCT_SUCCESS: 'Reviews fetched by product ID successfully',
    FETCH_USER_SUCCESS: 'Reviews fetched by user ID successfully',
    FETCH_ONE_SUCCESS: 'Review details fetched successfully',
    UPDATE_SUCCESS: 'Review updated successfully',
    DELETE_SUCCESS: 'Review deleted successfully',
  },
  WISHLIST: {
    FETCH_USER_SUCCESS: 'Wishlist retrieved successfully',
    ADD_ITEM_SUCCESS: 'Product added to wishlist successfully',
    REMOVE_ITEM_SUCCESS: 'Wishlist item removed successfully',
  },
  INVENTORY: {
    FETCH_ALL_SUCCESS: 'Inventory records fetched successfully',
    FETCH_LOW_STOCK_SUCCESS: 'Low stock inventory items fetched successfully',
    FETCH_ALL_HISTORY_SUCCESS: 'All inventory history logs fetched successfully',
    FETCH_VP_HISTORY_SUCCESS: 'Inventory history logs fetched by vendor product ID successfully',
    FETCH_VP_SUCCESS: 'Inventory fetched by vendor product ID successfully',
    ADJUST_SUCCESS: 'Inventory stock adjusted successfully',
    RESERVE_SUCCESS: 'Inventory stock reserved successfully',
    RELEASE_SUCCESS: 'Inventory stock released successfully',
    DEDUCT_SUCCESS: 'Inventory stock deducted successfully',
  },
  LOCATION: {
    FETCH_COUNTRIES_SUCCESS: 'Countries fetched successfully',
    FETCH_STATES_SUCCESS: 'States fetched successfully',
    FETCH_CITIES_SUCCESS: 'Cities fetched successfully',
    CREATE_ADDRESS_SUCCESS: 'Address created successfully',
    FETCH_USER_ADDRESSES_SUCCESS: 'User addresses fetched successfully',
    FETCH_ADDRESS_ONE_SUCCESS: 'Address details fetched successfully',
    UPDATE_ADDRESS_SUCCESS: 'Address updated successfully',
    DELETE_ADDRESS_SUCCESS: 'Address deleted successfully',
    SET_DEFAULT_ADDRESS_SUCCESS: 'Default address set successfully',
  },
  USERS: {
    FETCH_ALL_SUCCESS: 'Users fetched successfully',
    FETCH_ONE_SUCCESS: 'User details fetched successfully',
  },
};
